/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef LWFSTB_H
#define LWFSTB_H

/* function declarations */
void init_lwfstb(void);
Netsnmp_Node_Handler handle_lwfwifi0enable;
Netsnmp_Node_Handler handle_lwfwifi0ssid;
Netsnmp_Node_Handler handle_lwfwifi0keymgmt;
Netsnmp_Node_Handler handle_lwfwifi0encryptionm;
Netsnmp_Node_Handler handle_lwfwifi0password;
Netsnmp_Node_Handler handle_lwfwifi0phymode;
Netsnmp_Node_Handler handle_lwfwifi0networkmode;
Netsnmp_Node_Handler handle_lwfwifi0ssidbroadcast;
Netsnmp_Node_Handler handle_lwfwifi0channel;
Netsnmp_Node_Handler handle_lwfwifi0bandwidth;
Netsnmp_Node_Handler handle_wfwifi0txpower;
Netsnmp_Node_Handler handle_lwfusername;
Netsnmp_Node_Handler handle_lwfpassword;
Netsnmp_Node_Handler handle_lwffactoryrestore;
Netsnmp_Node_Handler handle_lwfreboot;
Netsnmp_Node_Handler handle_lwfsupersettingsenable;
Netsnmp_Node_Handler handle_lwfssidmodifyenable;
Netsnmp_Node_Handler handle_lwfwifi0ssidheader;
Netsnmp_Node_Handler handle_lwfwifi1ssid;
Netsnmp_Node_Handler handle_lwfwifi0mac;
Netsnmp_Node_Handler handle_lwfwanlink;
Netsnmp_Node_Handler handle_lwfwanip;
Netsnmp_Node_Handler handle_lwfwanmask;
Netsnmp_Node_Handler handle_lwfwandns1;
Netsnmp_Node_Handler handle_lwfwandns2;
Netsnmp_Node_Handler handle_lwflanmac;
Netsnmp_Node_Handler handle_lwflanip;
Netsnmp_Node_Handler handle_lwflanmask;
Netsnmp_Node_Handler handle_lwfwifi0wpsenable;
Netsnmp_Node_Handler handle_lwfwifi0wpspin;
Netsnmp_Node_Handler handle_lwfwifi0wpsstart;
Netsnmp_Node_Handler handle_lwfwifi0wpsstatus;
Netsnmp_Node_Handler handle_lwfwifi0wdsremotemac;
Netsnmp_Node_Handler handle_lwfapplysettings;

/* function declarations */
void init_lwfstb(void);

void initialize_table_dhcpclientTable(void);
Netsnmp_Node_Handler dhcpclientTable_handler;
Netsnmp_First_Data_Point  dhcpclientTable_get_first_data_point;
Netsnmp_Next_Data_Point   dhcpclientTable_get_next_data_point;
void buildhcpclienttable();

void initialize_table_wifistationTable(void);
Netsnmp_Node_Handler wifistationTable_handler;
Netsnmp_First_Data_Point  wifistationTable_get_first_data_point;
Netsnmp_Next_Data_Point   wifistationTable_get_next_data_point;
void buildwifistationtable();

/* column number definitions for table dhcpclientTable */
       #define COLUMN_CLIENTINDEX		1
       #define COLUMN_CLIENTMAC		2
       #define COLUMN_CLIENTIP		3
       #define COLUMN_CLIENTLEASETIME		4

/* column number definitions for table wifistationTable */
       #define COLUMN_STATIONINDEX		1
       #define COLUMN_STATIONMAC		2
       #define COLUMN_ASSOCTIME		3

#endif /* LWFSTB_H */
